# Generated by Django 3.1.7 on 2021-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='symbol',
            field=models.CharField(default='Symbol', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category name', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expenses', 'expenses'), ('savings', 'savings')], default='income', max_length=8),
        ),
    ]
